import { defineStore } from "pinia";

export const useExampleStore = defineStore("useExampleStore", {
  state: () => ({
    modal: false,
    listCandidatos: [],
    candidato: {
      nombre: null,
      estatus: null,
      distrito: null,
      partido: null,
      fecha_Registro: null,
      fotografia: null,
      genero: null,
    },
  }),
  actions: {
    actualizarModal(valor) {
      this.modal = valor;
      console.log(valor);
    },
    async loadCandidatos() {
      this.listCandidatos = [
        {
          id: 1,
          id_grupo: 1,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Diputación",
          tipo_Eleccion: "MR",
          distrito: "1",
          partido: "Partido",
          progreso: 30,
          puntuacion: 30,
          cargo: "Propietario",
          genero: "Mujer",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
          coalicion: true,
          nombre_Coalicion: "nombre coalicion",
          imgPartido2:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          imgPartido3:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
        },
        {
          id: 2,
          id_grupo: 1,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Diputación",
          tipo_Eleccion: "MR",
          distrito: "2",
          partido: "Partido",
          progreso: 100,
          puntuacion: 100,
          genero: "Hombre",
          cargo: "Suplente",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          coalicion: true,
          nombre_Coalicion: "nombre coalicion",
          imgPartido2:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          imgPartido3:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
        },
        {
          id: 3,
          id_grupo: 3,
          orden_Prelacion: 3,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Diputación",
          tipo_Eleccion: "RP",
          partido: "Partido",
          progreso: 80,
          puntuacion: 80,
          genero: "Hombre",
          cargo: "Propietario",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRD.png",
          coalicion: false,
        },
        {
          id: 4,
          id_grupo: 4,
          orden_Prelacion: 4,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Diputación",
          tipo_Eleccion: "RP",
          distrito: "",
          partido: "Partido",
          progreso: 30,
          puntuacion: 30,
          cargo: "Propietario",
          genero: "No binario",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
          coalicion: true,
          nombre_Coalicion: "nombre coalicion",
          imgPartido2:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          imgPartido3:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
        },
        {
          id: 5,
          id_grupo: 5,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Diputación",
          tipo_Eleccion: "MR",
          distrito: "1",
          partido: "Partido",
          progreso: 30,
          puntuacion: 30,
          cargo: "Propietario",
          genero: "Hombre",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
          coalicion: true,
          nombre_Coalicion: "nombre coalicion",
          imgPartido2:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          imgPartido3:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
        },
        {
          id: 6,
          id_grupo: 6,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Presidencia y Sindicaturas",
          partido: "Partido",
          municipio: "Tepic",
          progreso: 80,
          puntuacion: 80,
          genero: "No binario",
          cargo: "Propietario",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/MORENA.png",
          coalicion: true,
          nombre_Coalicion: "nombre coalicion",
          imgPartido2:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PRI.png",
          imgPartido3:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/PAN.png",
        },
        {
          id: 7,
          id_grupo: 7,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Presidencia y Sindicaturas",
          partido: "Partido",
          municipio: "Tepic",
          progreso: 80,
          puntuacion: 80,
          cargo: "Propietario",
          genero: "Mujer",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/MORENA.png",
          coalicion: false,
        },
        {
          id: 8,
          id_grupo: 8,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Regidurias",
          tipo_Eleccion: "MR",
          partido: "Partido",
          municipio: "Tepic",
          demarcacion: "2",
          progreso: 80,
          puntuacion: 80,
          cargo: "Propietario",
          genero: "Hombre",
          fecha_Registro: "20/10/2023",
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/MORENA.png",
          coalicion: false,
        },
        {
          id: 9,
          id_grupo: 9,
          nombre: "Nombre",
          estatus: "Activo",
          tipo: "Regidurias",
          tipo_Eleccion: "RP",
          partido: "Partido",
          municipio: "Tepic",
          progreso: 80,
          puntuacion: 80,
          cargo: "Propietario",
          genero: "Hombre",
          fecha_Registro: "20/10/2023",
          orden_Prelacion: 1,
          fotografia: "https://cdn-icons-png.flaticon.com/512/3177/3177440.png",
          imgPartido:
            "https://www.prepnayarit2021.com/storage/actas_digitales/midaec/logos_partidos/MORENA.png",
          coalicion: false,
        },
      ];
    },
  },
});
